<a href="https://colab.research.google.com/github/siliconemonster/IA-2020.1/blob/main/Hill_Climbing_e_Simulated_Annealing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1> HILL CLIMBING E SIMULATED ANNEALING**


## **Nesta tarefa você vai implementar os algoritmos Hill Climbing e Simulated Annealing e usá-los para resolver o problema das N-Rainhas. Os programas devem ser feitos preferencialmente na linguagem Python.**
1. Modelagem
<br>(a) Descreva como um tabuleiro N × N com N rainhas é representado no seu programa.
2. Implementação: As seguintes funções devem ser implementadas de maneira que possam ser testadas individualmente.
<br>(a) Defina uma função que dado o tamanho do tabuleiro N, retorna um tabuleiro N ×N com N rainhas.
O tabuleiro deve ser gerado de maneira aleatória.
<br>(b) Defina uma função que dado um tabuleiro qualquer, retorna todos os seus vizinhos.
<br>(c) Defina uma função que dado um tabuleiro qualquer, retorna um de seus vizinhos. A escolha do vizinho a ser retornado pela função deve ser aleatória.
<br>(d) Defina uma função que dado um tabuleiro qualquer, retorna a avaliação deste tabuleiro (número de ataques entre as rainhas).
3. Hill Climbing
<br>(a) Implemente uma versão do algoritmo Hill Climbing, onde o tabuleiro sucessor do tabuleiro corrente será o primeiro vizinho dele (tabuleiro corrente) que tem uma avaliação melhor. Assim, se a avaliação do tabuleiro corrente Tc for igual a k, o primeiro tabuleiro vizinho de Tc encontrado com avaliação menor que k deve passar a ser o novo tabuleiro corrente.
<br>(b) Implemente uma versão do algoritmo Hill Climbing, onde todos os tabuleiros vizinhos do tabuleiro corrente são avaliados e escolha para ser o novo tabuleiro corrente aquele que mais melhora a avaliação do tabuleiro corrente atual. No caso de haver mais de um tabuleiro, a escolha deve ser
feita de forma aleatória.
<br>(c) Analise o desempenho de cada umas das implementações. Considere:
 Tabuleiros de tamanho 4, 8, 16 e 32.
 Para cada tamanho de tabuleiro:<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Indique quantas vezes você precisou executar os programas para encontrar uma solução.<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Quantos tabuleiros correntes, em média, foram gerados em cada execução dos programas.
<br>(d) Quais conclusões você consegue tirar destes experimentos?
4. Simulated Annealing
<br>(a) Implemente o algoritmo Simulated Annealing. Os parâmetros de entrada do programa devem ser temperatura inicial TempInicial, o número máximo de iterações MaxIt e o fator de decaimento α.
<br>(b) Determine experimentalmente valores para os parâmetros de entrada que permitam que uma solução
seja encontrada. Considere apenas tabuleiros de tamanho 4 e 8. Relate como a busca se comportou para os diferentes valores dos parâmetros de entrada que você usou.
<br>(c) Caso você tenha sido bem sucedido no item anterior (encontrou a solução do problema de 4 e 8 rainhas), use os mesmos parâmetros de entrada usados e execute o programa agora considerando tabuleiros de tamanho 16 e 32. O que acontece?
5. Comparando os métodos Hill Climbing e Simulated Annealing na resolução do problema das N-rainhas, o que você pode concluir?

--------------------------------------------------------------------------------

<h2>1 - Modelagem

<h3>a) Representação inicial do tabuleiro:

In [179]:
import numpy as np

x = 4
tabuleiroVazio = np.zeros((1, x), dtype=int)
print(tabuleiroVazio)

[[0 0 0 0]]


No caso de um tabuleiro 4x4, como o caso acima, temos um vetor de 1x4, vazio. Só pode haver uma rainha por coluna, então a coluna em que existir uma, será representada pelo número da linha.<br>
**Por exemplo:**<br>
Um tabuleiro do tipo: <br>
[0 &nbsp; 0 &nbsp; 0 &nbsp; 0]<br>
[R &nbsp; 0 &nbsp; 0 &nbsp; R]<br>
[0 &nbsp; R &nbsp; 0 &nbsp; 0]<br>
[0 &nbsp; 0 &nbsp; R &nbsp; 0]<br>
onde 0 representa onde está vazio, e R representa onde há uma rainha; na modelagem em questão, é representado por: <br>
[2 &nbsp; 3 &nbsp; 4 &nbsp; 2]

<h2> 2 - Implementação

<h3>a) Definir uma função que retorna o tabuleiro aleatório:

In [214]:
import numpy as np
import random

def geraTabuleiro(n):
  tabuleiro = np.zeros(( n), dtype=int)
  #print(tabuleiro)

  for x in range(n):
    posicaoRainha = random.randint(1, n)
    #print(posicaoRainha)
    tabuleiro[x] = posicaoRainha

  print("Tabuleiro Atual:")
  print(tabuleiro)
  return tabuleiro

geraTabuleiro(4)

Tabuleiro Atual:
[3 4 4 3]


array([3, 4, 4, 3])

<h3> b) Definir uma função que retorna vizinhos:

In [209]:
def geraVizinhos(n, tabuleiroAtual):
  quantViz = (n-1)*n # cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizinhos = np.zeros((quantViz, n), dtype=int)

  indice = 0
  for i in range (n):
    for j in range (1,n+1):
      if tabuleiroAtual[i]!=j:
        aux = []
        aux = tabuleiroAtual.copy()
        aux[i] = j
        vizinhos[indice] = aux
        indice = indice + 1

  print("Vizinhos:")
  print(vizinhos)
  return vizinhos

tabuleiro = geraTabuleiro(4)
geraVizinhos(4, tabuleiro)

Tabuleiro Atual:
[2 3 2 3]
Vizinhos:
[[1 3 2 3]
 [3 3 2 3]
 [4 3 2 3]
 [2 1 2 3]
 [2 2 2 3]
 [2 4 2 3]
 [2 3 1 3]
 [2 3 3 3]
 [2 3 4 3]
 [2 3 2 1]
 [2 3 2 2]
 [2 3 2 4]]


array([[1, 3, 2, 3],
       [3, 3, 2, 3],
       [4, 3, 2, 3],
       [2, 1, 2, 3],
       [2, 2, 2, 3],
       [2, 4, 2, 3],
       [2, 3, 1, 3],
       [2, 3, 3, 3],
       [2, 3, 4, 3],
       [2, 3, 2, 1],
       [2, 3, 2, 2],
       [2, 3, 2, 4]])

<h3>c) Definir uma função que gera um vizinho aleatório

In [215]:
def vizinhoAleatorio(n, vizinhos):
  quantViz = (n-1)*n # cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizAleatorio = np.zeros(( n), dtype=int)

  posicao = random.randint(0, (quantViz-1))

  for x in range(n):
    vizAleatorio[x] = vizinhos[posicao][x]

  print("Vizinho aleatório:")
  print(vizAleatorio)
  return vizAleatorio

tabuleiro = geraTabuleiro(4)
vizinhos = geraVizinhos(4, tabuleiro)
vizinhoAleatorio(4, vizinhos)

Tabuleiro Atual:
[4 1 1 4]
Vizinhos:
[[1 1 1 4]
 [2 1 1 4]
 [3 1 1 4]
 [4 2 1 4]
 [4 3 1 4]
 [4 4 1 4]
 [4 1 2 4]
 [4 1 3 4]
 [4 1 4 4]
 [4 1 1 1]
 [4 1 1 2]
 [4 1 1 3]]
Vizinho aleatório:
[4 4 1 4]


array([4, 4, 1, 4])

<h3>d) Definir uma função que conta o número de ataques

In [216]:
def avaliaAtaques(n, tabuleiro):
  ataques = 0

  for i in range(n-1): # caso esteja na mesma coluna
    for j in range(i+1, n):
      if (tabuleiro[i] == tabuleiro[j]):
        ataques = ataques + 1

  for i in range(n-1): # caso esteja na mesma diagonal. Para baixo e para cima, respectivamente
    for j in range(i+1, n):
      if ((tabuleiro[i] == tabuleiro[j] + (j - i)) or (tabuleiro[i] == tabuleiro[j] - (j - i))):
        ataques = ataques + 1

  #print("Número de ataques:")
  print(ataques)
  return ataques

tabuleiro = geraTabuleiro(4)
avaliaAtaques(4, tabuleiro)

Tabuleiro Atual:
[4 2 1 2]
3


3

<h2>3 - Hill Climbing

<h3>a) Definir uma versão do algoritmo Hill Climbing, onde o tabuleiro sucessor do tabuleiro corrente será o primeiro vizinho dele que tem uma avaliação melhor

In [217]:
def hillClimbingPrimeiro (n, estadoInicial):
  corrente = estadoInicial
  
  while True:
    vizinhos = geraVizinhos(n, corrente)
    size = len(vizinhos)
    h = np.zeros(size, dtype=int)

    for i in range(size):
      aux = vizinhos[i]
      h[i] = avaliaAtaques(n, aux) # h[i] representa a heurística do vizinho[i]

    # hill climbing começa de fato aqui
    hCorr = avaliaAtaques(n, corrente) # heurística do nó corrente
    fCorr = -hCorr # função objetivo do nó corrente
    for i in range(size):
      if (i == 0):
        proximo = h[i]
        pos = 0
      elif (h[i] < proximo):
        proximo = h[i] # pega o primeiro menor ataque
        pos = i # pega a posição onde está o menor ataque
    vizinho = vizinhos[pos]
    hViz = h[pos] # heurística do nó vizinho
    fViz = -hViz # função objetivo do nó vizinho
    if (fViz <= fCorr):
      return corrente
    corrente = vizinho # atualiza o novo estado atual
    print("Novo - Tabuleiro Atual:")
    print(corrente)

estadoInicial = geraTabuleiro(4)
hillClimbingPrimeiro(4, estadoInicial)

Tabuleiro Atual:
[3 3 4 1]
Vizinhos:
[[1 3 4 1]
 [2 3 4 1]
 [4 3 4 1]
 [3 1 4 1]
 [3 2 4 1]
 [3 4 4 1]
 [3 3 1 1]
 [3 3 2 1]
 [3 3 3 1]
 [3 3 4 2]
 [3 3 4 3]
 [3 3 4 4]]
3
4
5
1
1
2
4
4
4
2
5
3
3
Novo - Tabuleiro Atual:
[3 1 4 1]
Vizinhos:
[[1 1 4 1]
 [2 1 4 1]
 [4 1 4 1]
 [3 2 4 1]
 [3 3 4 1]
 [3 4 4 1]
 [3 1 1 1]
 [3 1 2 1]
 [3 1 3 1]
 [3 1 4 2]
 [3 1 4 3]
 [3 1 4 4]]
3
3
3
1
3
2
4
3
2
0
3
1
1
Novo - Tabuleiro Atual:
[3 1 4 2]
Vizinhos:
[[1 1 4 2]
 [2 1 4 2]
 [4 1 4 2]
 [3 2 4 2]
 [3 3 4 2]
 [3 4 4 2]
 [3 1 1 2]
 [3 1 2 2]
 [3 1 3 2]
 [3 1 4 1]
 [3 1 4 3]
 [3 1 4 4]]
1
3
1
2
2
3
3
2
2
1
3
1
0


array([3, 1, 4, 2])

<h3>b) Definir uma versão do algoritmo Hill Climbing, onde todos os tabuleiros vizinhos do tabuleiro corrente são avaliados e escolha para ser o novo tabuleiro corrente aquele que mais melhora a avaliação do tabuleiro corrente atual. No caso de haver mais de um tabuleiro, a escolha deve ser
feita de forma aleatória.

In [218]:
def hillClimbingAleatorio (n, estadoInicial):
  corrente = estadoInicial
  
  while True:
    vizinhos = geraVizinhos(n, corrente)
    size = len(vizinhos)
    h = np.zeros(size, dtype=int)
    pos = np.zeros(size, dtype=int)

    for i in range(size): # preencher o vetor de posições com -1
      pos[i] = -1

    for i in range(size):
      aux = vizinhos[i]
      h[i] = avaliaAtaques(n, aux) # h[i] representa a heurística do vizinho[i]

    # hill climbing começa de fato aqui
    hCorr = avaliaAtaques(n, corrente) # heurística do nó corrente
    fCorr = -hCorr # função objetivo do nó corrente

    for i in range(size):
      if (i == 0):
        proximo = h[i]
      elif (h[i] < proximo):
        proximo = h[i] # descobre o menor ataque

    aux = 0
    for i in range(size): # no vetor de -1's, 
      if (h[i] == proximo): # os índices de onde os vizinhos de menor h 
        pos[aux] = i # são salvos nas primeiras posições de pos[]
        aux = aux + 1

    print("-----------")
    print("Vetor pos[] que guarda as posições de vizinhos de menor h[] (desconsiderar onde houver -1)")
    print(pos)

    posicao = random.randint(0, (aux-1)) # escolho um valor aleatório entre as posições de pos que foram de fato alteradas
    print("Posição aleatória do vetor acima:")
    print(posicao)

    indice = pos[posicao] # esse índice recebe o exato valor aleatório mencionado anteriormente
    print("Índice original escolhido aleatoriamente:")
    print(indice)
    
    vizinho = vizinhos[indice] # Sugiro descomentar os 4 últimos prints para ajudar na visualização
    print("Vizinho da posição do índice aleatório")
    print(vizinho)
    hViz = h[posicao] # heurística do nó vizinho
    fViz = -hViz # função objetivo do nó vizinho
    if (fViz <= fCorr):
      return corrente
    corrente = vizinho # atualiza o novo estado atual
    print("-----------")
    print("-----------")
    print("Novo - Tabuleiro Atual:")
    print(corrente)

estadoInicial = geraTabuleiro(4)
hillClimbingAleatorio(4, estadoInicial)

Tabuleiro Atual:
[1 3 3 3]
Vizinhos:
[[2 3 3 3]
 [3 3 3 3]
 [4 3 3 3]
 [1 1 3 3]
 [1 2 3 3]
 [1 4 3 3]
 [1 3 1 3]
 [1 3 2 3]
 [1 3 4 3]
 [1 3 3 1]
 [1 3 3 2]
 [1 3 3 4]]
4
6
4
4
4
3
2
3
3
4
3
4
4
-----------
Vetor pos[] que guarda as posições de vizinhos de menor h[] (desconsiderar onde houver -1)
[ 6 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
Posição aleatória do vetor acima:
0
Índice original escolhido aleatoriamente:
6
Vizinho da posição do índice aleatório
[1 3 1 3]


array([1, 3, 3, 3])

<h3>c) Analise o desempenho de cada umas das implementações. Considere: Tabuleiros de tamanho 4, 8, 16 e 32. Para cada tamanho de tabuleiro:
        – Indique quantas vezes você precisou executar os programas para encontrar uma solução.
        – Quantos tabuleiros correntes, em média, foram gerados em cada execução dos programas.


bla

<h3>d) Quais conclusões você consegue tirar destes experimentos?

bla

<h2> Simulated Annealing

<h3>a) Implemente o algoritmo Simulated Annealing. Os parâmetros de entrada do programa devem ser temperatura inicial TempInicial, o número máximo de iterações MaxIt e o fator de decaimento α.
(b) Determine experimentalmente valores para os parâmetros de entrada que permitam que uma solução seja encontrada. Considere apenas tabuleiros de tamanho 4 e 8. Relate como a busca se comportou para os diferentes valores dos parâmetros de entrada que você usou.
(c) Caso você tenha sido bem sucedido no item anterior (encontrou a solução do problema de 4 e 8 rainhas), use os mesmos parâmetros de entrada usados e execute o programa agora considerando tabuleiros de tamanho 16 e 32. O que acontece?