<a href="https://colab.research.google.com/github/siliconemonster/IA-2020.1/blob/main/Hill_Climbing_e_Simulated_Annealing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Nesta tarefa você vai implementar os algoritmos Hill Climbing e Simulated Annealing e usá-los para resolver o problema das N-Rainhas. Os programas devem ser feitos preferencialmente na linguagem Python.**
1. Modelagem
<br>(a) Descreva como um tabuleiro N × N com N rainhas é representado no seu programa.
2. Implementação: As seguintes funções devem ser implementadas de maneira que possam ser testadas individualmente.
<br>(a) Defina uma função que dado o tamanho do tabuleiro N, retorna um tabuleiro N ×N com N rainhas.
O tabuleiro deve ser gerado de maneira aleatória.
<br>(b) Defina uma função que dado um tabuleiro qualquer, retorna todos os seus vizinhos.
<br>(c) Defina uma função que dado um tabuleiro qualquer, retorna um de seus vizinhos. A escolha do vizinho a ser retornado pela função deve ser aleatória.
<br>(d) Defina uma função que dado um tabuleiro qualquer, retorna a avaliação deste tabuleiro (número de ataques entre as rainhas).
3. Hill Climbing
<br>(a) Implemente uma versão do algoritmo Hill Climbing, onde o tabuleiro sucessor do tabuleiro corrente será o primeiro vizinho dele (tabuleiro corrente) que tem uma avaliação melhor. Assim, se a avaliação do tabuleiro corrente Tc for igual a k, o primeiro tabuleiro vizinho de Tc encontrado com avaliação menor que k deve passar a ser o novo tabuleiro corrente.
<br>(b) Implemente uma versão do algoritmo Hill Climbing, onde todos os tabuleiros vizinhos do tabuleiro corrente são avaliados e escolha para ser o novo tabuleiro corrente aquele que mais melhora a avaliação do tabuleiro corrente atual. No caso de haver mais de um tabuleiro, a escolha deve ser
feita de forma aleatória.
<br>(c) Analise o desempenho de cada umas das implementações. Considere:
 Tabuleiros de tamanho 4, 8, 16 e 32.
 Para cada tamanho de tabuleiro:<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Indique quantas vezes você precisou executar os programas para encontrar uma solução.<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Quantos tabuleiros correntes, em média, foram gerados em cada execução dos programas.
<br>(d) Quais conclusões você consegue tirar destes experimentos?
4. Simulated Annealing
<br>(a) Implemente o algoritmo Simulated Annealing. Os parâmetros de entrada do programa devem ser temperatura inicial TempInicial, o número máximo de iterações MaxIt e o fator de decaimento α.
<br>(b) Determine experimentalmente valores para os parâmetros de entrada que permitam que uma solução
seja encontrada. Considere apenas tabuleiros de tamanho 4 e 8. Relate como a busca se comportou para os diferentes valores dos parâmetros de entrada que você usou.
<br>(c) Caso você tenha sido bem sucedido no item anterior (encontrou a solução do problema de 4 e 8 rainhas), use os mesmos parâmetros de entrada usados e execute o programa agora considerando tabuleiros de tamanho 16 e 32. O que acontece?
5. Comparando os métodos Hill Climbing e Simulated Annealing na resolução do problema das N-rainhas, o que você pode concluir?

--------------------------------------------------------------------------------

<h2>1 Modelagem

<h3>a) Representação inicial do tabuleiro:

In [200]:
import numpy as np

x = 4
tabuleiroVazio = np.zeros((1, x), dtype=int)
print(tabuleiroVazio)

[[0 0 0 0]]


No caso de um tabuleiro 4x4, como o caso acima, temos um vetor de 1x4, vazio. Só pode haver uma rainha por coluna, então a coluna em que existir uma, será representada pelo número da linha.<br>
**Por exemplo:**<br>
Um tabuleiro do tipo: <br>
[0 &nbsp; 0 &nbsp; 0 &nbsp; 0]<br>
[R &nbsp; 0 &nbsp; 0 &nbsp; R]<br>
[0 &nbsp; R &nbsp; 0 &nbsp; 0]<br>
[0 &nbsp; 0 &nbsp; R &nbsp; 0]<br>
onde 0 representa onde está vazio, e R representa onde há uma rainha; na modelagem em questão, é representado por: <br>
[2 &nbsp; 3 &nbsp; 4 &nbsp; 2]

<h2> 2 - Implementação

<h3>a) Definir uma função que retorna o tabuleiro aleatório:

In [201]:
import numpy as np
import random

def geraTabuleiro(n):
  tabuleiro = np.zeros((1, n), dtype=int)
  #print(tabuleiro)

  for x in range(n):
    posicaoRainha = random.randint(1, n)
    #print(posicaoRainha)
    tabuleiro[0][x] = posicaoRainha

  #print(tabuleiro)
  return tabuleiro

geraTabuleiro(4)

array([[3, 3, 1, 3]])

<h3> b) Definir uma função que retorna vizinhos:

In [222]:
def geraVizinhos(n, tabuleiroAtual):
  quantViz = (n-1)*n #cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizinhos = np.zeros((quantViz, n), dtype=int)
  print("Tabuleiro Atual:")
  print(tabuleiroAtual)

  for x in range(quantViz): #laço for para salvar o mesmo tabuleiro atual em todas as linhas de vizinhos
    for y in range(n):
      vizinhos[x][y] = tabuleiroAtual[0][y]

  for y in range(n):
    temp = vizinhos[0][y] #é a primeira posição de cada coluna
    for x in range (n-1): #se temos 3 números, ele já é 1 e teremos 2 alterações
      temp = ((temp + 1) % n) + 1 #usei o módulo para quando somar ao último número possível, ele ciclar. Somei 1 porque não desejo o valor 0
      vizinhos[x+y*(n-1)][y] = temp # y*(n-1) serve para pular as linhas onde alterei na iteração anterior

  print("Vizinhos:")
  print(vizinhos)
  return vizinhos

tabuleiro = geraTabuleiro(3)
geraVizinhos(3, tabuleiro)

Tabuleiro Atual:
[[1 3 2]]
Vizinhos:
[[3 3 2]
 [2 3 2]
 [1 2 2]
 [1 1 2]
 [1 3 1]
 [1 3 3]]


array([[3, 3, 2],
       [2, 3, 2],
       [1, 2, 2],
       [1, 1, 2],
       [1, 3, 1],
       [1, 3, 3]])

<h3>c) Definir uma função que gera um vizinho aleatório

In [223]:
def vizinhoAleatorio(n, vizinhos):
  quantViz = (n-1)*n #cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizAleatorio = np.zeros((1, n), dtype=int)

  posicao = random.randint(0, (quantViz-1))

  for x in range(n):
    vizAleatorio[0][x] = vizinhos[posicao][x]

  print("Vizinho aleatório:")
  print(vizAleatorio)
  return vizAleatorio

tabuleiro = geraTabuleiro(3)
vizinhos = geraVizinhos(3, tabuleiro)
vizinhoAleatorio(3, vizinhos)

Tabuleiro Atual:
[[3 3 2]]
Vizinhos:
[[2 3 2]
 [1 3 2]
 [3 2 2]
 [3 1 2]
 [3 3 1]
 [3 3 3]]
Vizinho aleatório:
[[2 3 2]]


array([[2, 3, 2]])