<a href="https://colab.research.google.com/github/siliconemonster/IA-2020.1/blob/main/Hill_Climbing_e_Simulated_Annealing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1> HILL CLIMBING E SIMULATED ANNEALING**


## **Nesta tarefa você vai implementar os algoritmos Hill Climbing e Simulated Annealing e usá-los para resolver o problema das N-Rainhas. Os programas devem ser feitos preferencialmente na linguagem Python.**
1. Modelagem
<br>(a) Descreva como um tabuleiro N × N com N rainhas é representado no seu programa.
2. Implementação: As seguintes funções devem ser implementadas de maneira que possam ser testadas individualmente.
<br>(a) Defina uma função que dado o tamanho do tabuleiro N, retorna um tabuleiro N ×N com N rainhas.
O tabuleiro deve ser gerado de maneira aleatória.
<br>(b) Defina uma função que dado um tabuleiro qualquer, retorna todos os seus vizinhos.
<br>(c) Defina uma função que dado um tabuleiro qualquer, retorna um de seus vizinhos. A escolha do vizinho a ser retornado pela função deve ser aleatória.
<br>(d) Defina uma função que dado um tabuleiro qualquer, retorna a avaliação deste tabuleiro (número de ataques entre as rainhas).
3. Hill Climbing
<br>(a) Implemente uma versão do algoritmo Hill Climbing, onde o tabuleiro sucessor do tabuleiro corrente será o primeiro vizinho dele (tabuleiro corrente) que tem uma avaliação melhor. Assim, se a avaliação do tabuleiro corrente Tc for igual a k, o primeiro tabuleiro vizinho de Tc encontrado com avaliação menor que k deve passar a ser o novo tabuleiro corrente.
<br>(b) Implemente uma versão do algoritmo Hill Climbing, onde todos os tabuleiros vizinhos do tabuleiro corrente são avaliados e escolha para ser o novo tabuleiro corrente aquele que mais melhora a avaliação do tabuleiro corrente atual. No caso de haver mais de um tabuleiro, a escolha deve ser
feita de forma aleatória.
<br>(c) Analise o desempenho de cada umas das implementações. Considere:
 Tabuleiros de tamanho 4, 8, 16 e 32.
 Para cada tamanho de tabuleiro:<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Indique quantas vezes você precisou executar os programas para encontrar uma solução.<br>
&nbsp; &nbsp; &nbsp; &nbsp; – Quantos tabuleiros correntes, em média, foram gerados em cada execução dos programas.
<br>(d) Quais conclusões você consegue tirar destes experimentos?
4. Simulated Annealing
<br>(a) Implemente o algoritmo Simulated Annealing. Os parâmetros de entrada do programa devem ser temperatura inicial TempInicial, o número máximo de iterações MaxIt e o fator de decaimento α.
<br>(b) Determine experimentalmente valores para os parâmetros de entrada que permitam que uma solução
seja encontrada. Considere apenas tabuleiros de tamanho 4 e 8. Relate como a busca se comportou para os diferentes valores dos parâmetros de entrada que você usou.
<br>(c) Caso você tenha sido bem sucedido no item anterior (encontrou a solução do problema de 4 e 8 rainhas), use os mesmos parâmetros de entrada usados e execute o programa agora considerando tabuleiros de tamanho 16 e 32. O que acontece?
5. Comparando os métodos Hill Climbing e Simulated Annealing na resolução do problema das N-rainhas, o que você pode concluir?

--------------------------------------------------------------------------------

<h2>1 - Modelagem

<h3>a) Representação inicial do tabuleiro:

In [27]:
import numpy as np
import random

x = 4
tabuleiroVazio = np.zeros((1, x), dtype=int)
print(tabuleiroVazio)

[[0 0 0 0]]


No caso de um tabuleiro 4x4, como o caso acima, temos um vetor de 1x4, vazio. Só pode haver uma rainha por coluna, então a coluna em que existir uma, será representada pelo número da linha.<br>
**Por exemplo:**<br>
Um tabuleiro do tipo: <br>
[0 &nbsp; 0 &nbsp; 0 &nbsp; 0]<br>
[R &nbsp; 0 &nbsp; 0 &nbsp; R]<br>
[0 &nbsp; R &nbsp; 0 &nbsp; 0]<br>
[0 &nbsp; 0 &nbsp; R &nbsp; 0]<br>
onde 0 representa onde está vazio, e R representa onde há uma rainha; na modelagem em questão, é representado por: <br>
[2 &nbsp; 3 &nbsp; 4 &nbsp; 2]

<h2> 2 - Implementação

<h3>a) Definir uma função que retorna o tabuleiro aleatório:

In [28]:
def geraTabuleiro(n):
  tabuleiro = np.zeros(( n), dtype=int)
  #print(tabuleiro)

  for x in range(n):
    posicaoRainha = random.randint(1, n)
    #print(posicaoRainha)
    tabuleiro[x] = posicaoRainha

  print("Tabuleiro Atual:")
  print(tabuleiro)
  return tabuleiro

geraTabuleiro(4)

Tabuleiro Atual:
[1 1 4 4]


array([1, 1, 4, 4])

<h3> b) Definir uma função que retorna vizinhos:

In [29]:
def geraVizinhos(n, tabuleiroAtual):
  quantViz = (n-1)*n # cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizinhos = np.zeros((quantViz, n), dtype=int)

  indice = 0
  for i in range(n):
    for j in range (1, n+1):
      if (tabuleiroAtual[i] != j):
        aux = []
        aux = tabuleiroAtual.copy()
        aux[i] = j
        vizinhos[indice] = aux
        indice = indice + 1

  #print("Vizinhos:")
  #print(vizinhos)
  return vizinhos

tabuleiro = geraTabuleiro(4)
geraVizinhos(4, tabuleiro)

Tabuleiro Atual:
[4 4 3 1]


array([[1, 4, 3, 1],
       [2, 4, 3, 1],
       [3, 4, 3, 1],
       [4, 1, 3, 1],
       [4, 2, 3, 1],
       [4, 3, 3, 1],
       [4, 4, 1, 1],
       [4, 4, 2, 1],
       [4, 4, 4, 1],
       [4, 4, 3, 2],
       [4, 4, 3, 3],
       [4, 4, 3, 4]])

<h3>c) Definir uma função que gera um vizinho aleatório

In [30]:
def vizinhoAleatorio(n, vizinhos):
  quantViz = (n-1)*n # cada dama pode ocupar n-1 novas posições, e são n damas. Um vizinho é uma única dama mudar de posição
  vizAleatorio = np.zeros(( n), dtype=int)

  posicao = random.randint(0, (quantViz-1))

  for x in range(n):
    vizAleatorio[x] = vizinhos[posicao][x]

  print("Vizinho aleatório:")
  print(vizAleatorio)
  return vizAleatorio

tabuleiro = geraTabuleiro(4)
vizinhos = geraVizinhos(4, tabuleiro)
vizinhoAleatorio(4, vizinhos)

Tabuleiro Atual:
[4 1 2 4]
Vizinho aleatório:
[4 1 4 4]


array([4, 1, 4, 4])

<h3>d) Definir uma função que conta o número de ataques

In [31]:
def avaliaAtaques(n, tabuleiro):
  ataques = 0

  for i in range(n-1): # caso esteja na mesma coluna
    for j in range(i+1, n):
      if (tabuleiro[i] == tabuleiro[j]):
        ataques = ataques + 1

  for i in range(n-1): # caso esteja na mesma diagonal. Para baixo e para cima, respectivamente
    for j in range(i+1, n):
      if ((tabuleiro[i] == tabuleiro[j] + (j - i)) or (tabuleiro[i] == tabuleiro[j] - (j - i))):
        ataques = ataques + 1
  if (ataques == 0):
    print("Número de ataques:")
    print(ataques)
  return ataques

tabuleiro = geraTabuleiro(4)
avaliaAtaques(4, tabuleiro)

Tabuleiro Atual:
[1 3 4 3]


3

<h2>3 - Hill Climbing

<h3>a) Definir uma versão do algoritmo Hill Climbing, onde o tabuleiro sucessor do tabuleiro corrente será o primeiro vizinho dele que tem uma avaliação melhor

In [32]:
def hillClimbingPrimeiro (n, estadoInicial):
  corrente = estadoInicial
  
  while True:
    vizinhos = geraVizinhos(n, corrente)
    size = len(vizinhos)
    h = np.zeros(size, dtype=int)

    for i in range(size):
      aux = vizinhos[i]
      h[i] = avaliaAtaques(n, aux) # h[i] representa a heurística do vizinho[i]

    # hill climbing começa de fato aqui
    hCorr = avaliaAtaques(n, corrente) # heurística do nó corrente
    fCorr = -hCorr # função objetivo do nó corrente
    for i in range(size):
      if (i == 0):
        proximo = h[i]
        pos = 0
      elif (h[i] < proximo):
        proximo = h[i] # pega o primeiro menor ataque
        pos = i # pega a posição onde está o menor ataque
    vizinho = vizinhos[pos]
    hViz = h[pos] # heurística do nó vizinho
    fViz = -hViz # função objetivo do nó vizinho
    if (fViz <= fCorr):
      return corrente
    corrente = vizinho # atualiza o novo estado atual
    print("Novo - Tabuleiro Atual:")
    print(corrente)

# caso de tabuleiro 4x4 perfeito
#estadoInicial = [2,4,1,3]

# caso de tabuleiro 8x8 perfeito
#estadoInicial = [7,5,3,1,6,8,2,4]

"""print("Tabuleiro Atual:")
print(estadoInicial)"""

estadoInicial = geraTabuleiro(4)
hillClimbingPrimeiro(4, estadoInicial)

Tabuleiro Atual:
[4 2 2 1]
Novo - Tabuleiro Atual:
[4 2 3 1]


array([4, 2, 3, 1])

<h3>b) Definir uma versão do algoritmo Hill Climbing, onde todos os tabuleiros vizinhos do tabuleiro corrente são avaliados e escolha para ser o novo tabuleiro corrente aquele que mais melhora a avaliação do tabuleiro corrente atual. No caso de haver mais de um tabuleiro, a escolha deve ser
feita de forma aleatória.

In [33]:
def hillClimbingAleatorio (n, estadoInicial):
  corrente = estadoInicial
  
  while True:
    vizinhos = geraVizinhos(n, corrente)
    size = len(vizinhos)
    h = np.zeros(size, dtype=int)
    pos = np.zeros(size, dtype=int)

    for i in range(size): # preencher o vetor de posições com -1
      pos[i] = -1

    for i in range(size):
      aux = vizinhos[i]
      h[i] = avaliaAtaques(n, aux) # h[i] representa a heurística do vizinho[i]

    # hill climbing começa de fato aqui
    hCorr = avaliaAtaques(n, corrente) # heurística do nó corrente
    fCorr = -hCorr # função objetivo do nó corrente

    for i in range(size):
      if (i == 0):
        proximo = h[i]
      elif (h[i] < proximo):
        proximo = h[i] # descobre o menor ataque

    aux = 0
    for i in range(size): # no vetor de -1's, 
      if (h[i] == proximo): # os índices de onde os vizinhos de menor h 
        pos[aux] = i # são salvos nas primeiras posições de pos[]
        aux = aux + 1

    #print("-----------")
    #print("Vetor pos[] que guarda as posições de vizinhos de menor h[] (desconsiderar onde houver -1)")
    #print(pos)

    posicao = random.randint(0, (aux-1)) # escolho um valor aleatório entre as posições de pos que foram de fato alteradas
    #print("Posição aleatória do vetor acima:")
    #print(posicao)

    indice = pos[posicao] # esse índice recebe o exato valor aleatório mencionado anteriormente
    #print("Índice original escolhido aleatoriamente:")
    #print(indice)
    
    vizinho = vizinhos[indice] # Sugiro descomentar os 4 últimos prints para ajudar na visualização
    #print("Vizinho da posição do índice aleatório")
    #print(vizinho)
    hViz = h[indice] # heurística do nó vizinho
    fViz = -hViz # função objetivo do nó vizinho
    """print("fViz:")
    print(fViz)"""
    if (fViz <= fCorr):
      return corrente
    corrente = vizinho # atualiza o novo estado atual
    #print("-----------")
    print("Novo - Tabuleiro Atual:")
    print(corrente)


# caso de tabuleiro 4x4 perfeito
#estadoInicial = [2,4,1,3]

# caso de tabuleiro 8x8 perfeito
#estadoInicial = [7,5,3,1,6,8,2,4]

"""print("Tabuleiro Atual:")
print(estadoInicial)"""

estadoInicial = geraTabuleiro(4)
hillClimbingAleatorio(4, estadoInicial)

Tabuleiro Atual:
[3 4 4 3]
Novo - Tabuleiro Atual:
[1 4 4 3]
Novo - Tabuleiro Atual:
[1 4 2 3]


array([1, 4, 2, 3])

<h3>c) Analise o desempenho de cada umas das implementações. Considere: Tabuleiros de tamanho 4, 8, 16 e 32. Para cada tamanho de tabuleiro:
        – Indique quantas vezes você precisou executar os programas para encontrar uma solução.
        – Quantos tabuleiros correntes, em média, foram gerados em cada execução dos programas.


4x4 - Foram gerados em média:
*   Primeiro menor (3a): 3 tabuleiros correntes quando encontrava a solução, e 2 tabuleiros correntes quando não encontrava. Encontrava solução 50% das tentativas.
*   Aleatório (3b): 3 tabuleiros correntes quando encontrava a solução, e 2 tabuleiros correntes quando não encontrava. Encontrava solução 50% das tentativas.


8x8 - Foram gerados em média:
*   Primeiro menor (3a): 6 tabuleiros correntes quando encontrava a solução, e 4 tabuleiros correntes quando não encontrava. Encontrava solução 50% das tentativas.
*   Aleatório (3b): 6 tabuleiros correntes quando encontrava a solução, e 4 tabuleiros correntes quando não encontrava. Encontrava solução 25% das tentativas.

16x16 - Foram gerados em média:
*   Primeiro menor (3a): 10 tabuleiros correntes quando encontrava a solução, e 8 tabuleiros correntes quando não encontrava. Encontrava solução 5% das tentativas.
*   Aleatório (3b):  7 tabuleiros correntes quando não encontrava solução. Não encontrou nenhuma solução.

32x32 - Foram gerados em média:
*   Primeiro menor (3a): 17 tabuleiros correntes quando não encontrava solução. Não encontrou nenhuma solução.
*   Aleatório (3b): 15 tabuleiros correntes quando não encontrava solução. Não encontrou nenhuma solução.

É possível que esses valores se alterem um pouco, conforme outras tentativas sejam feitas, porém não significativamente.

<h3>d) Quais conclusões você consegue tirar destes experimentos?

O algoritmo Hill Climbing é relativamente bom em casos onde o tabuleiro não é muito grande. Ele encontra a solução em aproximadamente metade das tentativas.<br>
As versões desse algoritmo onde se pega o primeiro vizinho de menor heurística e onde se pega um aleatório, dentre os de menor heurística, não fizeram muita diferença em relação a performances, com exceção no caso de 8x8, onde encontrou um pouco mais raramente ao usar o aleatório; e no caso de 16x16, onde o primeiro encontrou solução em alguns poucos casos, e o aleatório não encontrou em nenhum.<br>
O algoritmo não é eficiente para tabuleiros de n grandes, mesmo que a quantidade de casos aumente conforme esse n aumenta. Disso surge a necessidade de um outro algoritmo, o Simulated Annealing, implementado na próxima seção.


<h2>4 - Simulated Annealing

<h3>a) Definir o algoritmo Simulated Annealing


In [34]:
def simAnnealing(tempInicial, maxIt, alfa):
  n = 4
  corrente = geraTabuleiro(n)
  melhorEstado = corrente
  tempCorrente = tempInicial

  for i in range(maxIt):
    vizinhos = geraVizinhos(n, corrente)
    vizinho = vizinhoAleatorio(n, vizinhos)
    hMelhor = avaliaAtaques(n, melhorEstado)
    fMelhor = -hMelhor
    hCorr = avaliaAtaques(n, corrente)
    fCorr = -hCorr
    hViz = avaliaAtaques(n, vizinho)
    fViz = -hViz
    delta = fViz - fCorr
    if (delta <= 0):
      corrente = vizinho
      if (fViz <= fMelhor):
        melhorEstado = vizinho
    else:
      aleatorio = random.randint(0, 1)
      eulerPronto = np.exp((-delta)/tempCorrente)
      if (eulerPronto > aleatorio):
        corrente = vizinho

    tempCorrente = alfa * tempCorrente
    print(hCorr)
    return (melhorEstado, fMelhor)

simAnnealing(500, 50, 10)

Tabuleiro Atual:
[1 4 2 3]
Vizinho aleatório:
[1 4 2 1]
1


(array([1, 4, 2, 1]), -1)

<h3>b) Determine experimentalmente valores para os parâmetros de entrada que permitam que uma solução seja encontrada. Considere apenas tabuleiros de tamanho 4 e 8. Relate como a busca se comportou para os diferentes valores dos parâmetros de entrada que você usou.
(c) Caso você tenha sido bem sucedido no item anterior (encontrou a solução do problema de 4 e 8 rainhas), use os mesmos parâmetros de entrada usados e execute o programa agora considerando tabuleiros de tamanho 16 e 32. O que acontece?